### ISSUE TITLE
Improv. 2: Set the default zone 1 to “Global”

### ISSUE THREAD

**Issue by neojavan** [CCAFS/Analogues-Platform#19]
![image](https://cloud.githubusercontent.com/assets/1873836/2780230/e0b771a0-cb04-11e3-9105-760695ee4e00.png)

Currently if the default is not changed the analysis appears to run but no results map is produced.

Required action:
Code so that global data is used if the user does not change the reference site from the default “Zoom to country”.

Benefits:
The run will still be performed if people do not change the default setting

**Comment by htobon** [comment]
Verified.
