### ISSUE TITLE
Improv. 7: Script and other minor changes.

### ISSUE THREAD

**Issue by neojavan** [CCAFS/Analogues-Platform#23]
Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780520/71b9abfc-cb08-11e3-87b8-75f717798ef2.png)

Change to:
Climatic similarity
Areas that have higher similarity values more closely resemble the specified climate at the reference site

---

Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780512/6103c360-cb08-11e3-8d51-227beafc59dd.png)

Change to:
Spatial resolution of the dataset. 10 arc-minutes is approximately 19 km when measured at the equator while 30 arc-seconds is approximately 1 km. 

---

Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780502/4016348a-cb08-11e3-9307-27b5ea880051.png)

Change to:
The list of Global Climate Models (GCMs) for which data is available. You can choose specific GCMs or an ensemble which utilizes the mean of all available GCMs for that emissions scenario.

---

Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780494/3428e4a6-cb08-11e3-9b4c-63a3a70ca1bb.png)

Change to:
The time period over which current and future climates are calculated. 
NOTE: The time period used for climate projections is the 2030s decade (i.e. the years 2020-2049).

---

Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780481/000c660c-cb08-11e3-81b0-a16ce0b70fff.png)

Change to:
Threshold: if you select a threshold of 0.70 then the threshold shown on the summary page is 30%, it should read “0.70” (the new threshold is not a percentage)

---

Current:
![image](https://cloud.githubusercontent.com/assets/1873836/2780474/f3573856-cb07-11e3-9135-37e7095cc73d.png)

Change to:
Add Rotation to the Parameters used summary.

---

Benefits: Improved clarity of explanations

**Comment by neojavan** [comment]
Only last to add the Rotation to the Parameters used

**Comment by htobon** [comment]
Verified.
@neojavan will create a new issue only for the remained issue (Rotation to the parameters used).
Once the issue is created, would you please let us know here?
Thank you in advance.
