### ISSUE TITLE
Improv. 9: Too many options in the resolution dropdown tab

### ISSUE THREAD

**Issue by neojavan** [CCAFS/Analogues-Platform#25]
![image](https://cloud.githubusercontent.com/assets/1873836/2822046/257455bc-cf0e-11e3-8450-74dcf3551a41.png)

Too many options are given in the resolution dropdown tab and the greyed-out effect on unavailable options is not sufficiently clear.

Required action:
Dynamically change the dropdown tab to leave only the available options for that location. i.e this would currently leave 30 arc-seconds for country scale data or 2.5 and 10 arc-minutes for global data. 

Note: the options for the dropdown tab should not be short-cutted to only these values as large countries may be aggregated to coarser resolutions in the future and also continent scale data may be added with a currently unknown resolution

Benefits:
Users have a clearer idea of the resolution options available

**Comment by htobon** [comment]
Verified.
