### ISSUE TITLE
Integrate Analogues platform with Wordpress

### ISSUE THREAD

**Issue by neojavan** [CCAFS/Analogues-Platform#4]
Integrate Analogues platform with Wordpress
The header, footer, background and design of the blog should be seen in the platform, to demonstrate the integration of both sites.

**Comment by htobon** [comment]
I'm opening this issue again, since the Analogues Platform that needs to be embedded in the Blog is the production one and not the test version.

**Comment by neojavan** [comment]
@htobon this issue is ready, please check and close?

**Comment by htobon** [comment]
Verified :+1:
