### ISSUE TITLE
Improv. 1: Script for bioclims to work properly

### ISSUE THREAD

**Issue by neojavan** [CCAFS/Analogues-Platform#5]
Bioclims do not currently work because the number of divisions (ndivisions) in the input parameters is set to 12 (number of months in a year, for climatic data). 

Required action:
ndivisions needs to be set to 1 for the bioclims or 12 for climatic variables. 
Also the calendar and rotation section may be dynamically removed/greyed out if only bioclims are chosen because they are irrelevant for bioclimatic variables

Benefits:
Bioclims will work

Old name issue: Integrate the "Growing Season 2" and Bioclimatic Variables
This variables are in the platform, but don't get to the R execution.

**Comment by htobon** [comment]
In the "Label List", what does "Section: 2" mean?

**Comment by neojavan** [comment]
ndivisions issue will be set in a new issue #38. The validation for the calendar and rotation is implemented.
